### PR TITLE
Test administrator features with multisig

### PR DESCRIPTION
**Pull request by daveroga**
## What does this implement/fix? Explain your changes.
Fix: #963 . Test multisig functionality.
Fix some issue with the nonce of the multisig in `nightfall-administrator`. 

Test with `npm run test-administrator`

## Does this close any currently open issues?
Yes #963.

### CODE REVIEW

**Review by druiz0992 — COMMENTED** [review]
The abis/json included in the tests may require to update them from time to time if changes in contracts. Can’t you generate the json from latest version of contracts every time tests are launched?

**Comment by daveroga** [comment]
> The abis/json included in the tests may require to update them from time to time if changes in contracts. Can’t you generate the json from latest version of contracts every time tests are launched?

Yes. Changed this with the `getContractAbi` and the `contract-abi` endpoints developed in a previous PR.

**Review by druiz0992 — APPROVED** [review]

**Review by israelboudoux — APPROVED** [review]
Hey @daveroga, I have a question: are the files `multisig.mjs` and `nightfall-multisig.mjs` supposed to be under the `test` folder?

**Comment by daveroga** [comment]
> Hey @daveroga, I have a question: are the files `multisig.mjs` and `nightfall-multisig.mjs` supposed to be under the `test` folder?

This will be moved to the SDK to the role of administrator. We have to decide when to do it. Then we will refactor this and nightfall-administrator with the SDK

**Pull request merged**
