### PR TITLE
avoid storing redundant tx from blockpropose event

### LINKED ISSUE #667: Wallet to stop saving transactions it doesn't care about.
Since finalise withdrawal now only requires the transaction index and a siblingPath, there is no longer any need for all other transactions in a block to be stored.

We should remove this to save storage overhead in the browser.

### PR DESCRIPTION
**Pull request by LijuJoseJJ**
this PR for now fixes wallet/browser and nightfall_client
- only storing relevant transaction
- also only storing block object for which any transaction is stored to db

fixes #667

### CODE REVIEW

**Review by druiz0992 — CHANGES_REQUESTED** [review]
You will need to rebase with master and failing tests should now pass

**Review by druiz0992 — COMMENTED** [review]
Do we need to apply these changes to client-nightfall?

**Comment by LijuJoseJJ** [comment]
> Do we need to apply these changes to client-nightfall?

yes I believe, that why I refactored client as well in this PR

**Review by druiz0992 — COMMENTED** [review]
Can you think of how we can test this?

**Comment by LijuJoseJJ** [comment]
> Can you think of how we can test this?

the best way to test is (and the way i did is) to customise `erc20.test.mjs` for all scenario, I also run wallet app for case where client is not hosting a particular user (i.e keys are not store in client).

**Comment by israelboudoux** [comment]
Hey @LijuJoseJJ, are you still working on this PR?

**Comment by LijuJoseJJ** [comment]
> Hey @LijuJoseJJ, are you still working on this PR?

didn't notice merge conflict, will fix by tomorrow

**Review by druiz0992 — APPROVED** [review]

**Review by daveroga — APPROVED** [review]
LGTM

**Pull request merged**
