### PR TITLE
feat: update node and npm

### LINKED ISSUE #876: upgrade Node to latest lts
We should be using node v16 and npm 8 to get the latest features.  The upgrade needs to happen in the containers.  The `package-lock.json` files should be upgraded to the latest version via `npm upgrade` and dependencies resolved.

### PR DESCRIPTION
**Pull request by Westlad**
fixes #876
This PR updates Nightfall_3 to the latest LTS node (16.17) and the latest npm (8.15).

### CODE REVIEW

**Comment by pawelgrzybek** [comment]
Two little suggestions. We can add `engines` field to each of the package.json files. Some dev packages use these fields and can emit some helpful alerts. Also, we can put `.nvmrc` to the root level. Not thet it is necessary but `nvm` became such a popular version manager, that a lot of users can find it helpful (that should do `node -v > .nvmrc`).

Engines field:
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines

**Review by daveroga — APPROVED** [review]
LGTM

**Comment by pawelgrzybek** [comment]
@Westlad @daveroga I would also suggest changing base Docker image from `FROM node:14.17` to `FROM node:16.17` in:

- `optimist.standalone.Dockerfile`
- `hosted-utils-api-server/Dockerfile`

After this one I am happy to approve.

**Comment by Westlad** [comment]
> @Westlad @daveroga I would also suggest changing base Docker image from `FROM node:14.17` to `FROM node:16.17` in:
> 
> * `optimist.standalone.Dockerfile`
> * `hosted-utils-api-server/Dockerfile`
> 
> After this one I am happy to approve.

Oh, good spot. I missed those.

**Comment by Westlad** [comment]
> Personally I would also remove the part with got override. It is not in the scope of node.js update. In case we need to revert one piece of functionality or the other it is easier not to mix scopes like that. Sorry for being picky :)

No, it doesn't run without this.  The automated dependency check will fail so it's a necessary change for this PR, I'm not going to spend time splitting it out.

**Review by israelboudoux — CHANGES_REQUESTED** [review]
Hey @Westlad, with this upgrade our Github Actions pipeline should be upgraded too. Please, could you upgrade the node-version in the files under the folder `.github/workflows/`?

Thank you!

**Comment by Westlad** [comment]
> Hey @Westlad, with this upgrade our Github Actions pipeline should be upgraded too. Please, could you upgrade the node-version in the files under the folder `.github/workflows/`?
> 
> Thank you!

Good spot, thanks!

**Comment by pawelgrzybek** [comment]
Super minor, but also the `readme.md` needs little change.

From:

```
We have tested with versions 14.15.1 and 6.14.13 of `node` and `npm`, respectively.
```

To:

```
We have tested with versions 16.17.0 and 8.15.0 of `node` and `npm`, respectively.
```

**Review by pawelgrzybek — APPROVED** [review]

**Pull request merged**
