### PR TITLE
Refactor: Optimist to use all available CPUs 

### PR DESCRIPTION
**Pull request by pawelgrzybek**
## What does this implement/fix? Explain your changes.

It changes the way how we run optimist. [PM2](https://pm2.keymetrics.io) comes with a handy [Cluster Mode](https://pm2.keymetrics.io/docs/usage/cluster-mode/) that allows to scale app across all CPUs available.

To test it out, I emitted a multiple transactions using SDK. Every transition was handler by different CPU which is presented on the screen.

Screenshot 2023-02-23 at 17 42 17

## Any other comments?

Potentially it can beneficial for us to enable this mode on client. I am open for your feedback.

### CODE REVIEW

**Comment by israelboudoux** [comment]
A so simple solution. Good work @pawelgrzybek! How is the audience of this `pm2`?

**Comment by druiz0992** [comment]
If I understand this correctly, this mechanism dispatches requests addressed to port 80 to different cores. Is this so?

**Review by druiz0992 — CHANGES_REQUESTED** [review]
I have some concerns about this approach that I would like cleared before approving:
- Have you checked against potential race conditions?
- How do we add other requests to the parallelization? There are some events emitted from the smart contracts via a websocket in the optimist (`transaction submitted`) that could also be embedded in the parallelization. This is not super important, as most requests will be from http
- The `blockProposed` event and block production task should also be handled by a single different thread than main. How can we achieve this with pm2?

**Review by Westlad — CHANGES_REQUESTED** [review]
This uses a GPL Affero license.  We consider these licenses too restrictive because it would require us to issue Nightfall under a GPL license rather than as a creative common.

**Comment by pawelgrzybek** [comment]
I did a bit more research and looks like we already depend on at least few packages that depend on some variation of `GPL` license. Let me use this issue to document my findings and to further discuss this topic.

```
npm query ":attr([license*=GPL])" | jq '. | length'
> 85
```

```
npm query ":attr([license*=GPL])" | jq '.[] | .name'
> "@iden3/bigarray"
> "@iden3/binfileutils"
> "web3-utils"
> "web3-utils"
> "web3"
> "web3-bzz"
> "web3-core"
> "web3-core-helpers"
> "web3-core-method"
> "web3-core-promievent"
> "web3-core-requestmanager"
> "web3-core-subscriptions"
> "web3-eth"
> "web3-eth-abi"
> "web3-eth-accounts"
> "web3-eth-contract"
> "web3-eth-ens"
> "web3-eth-iban"
> "web3-eth-personal"
> "web3-net"
> "web3-providers-http"
> "web3-providers-ipc"
> "web3-providers-ws"
> "web3-shh"
> "web3-utils"
> "web3"
> "web3-bzz"
> "web3-core"
> "web3-core-helpers"
> "web3-core-method"
> "web3-core-promievent"
> "web3-core-requestmanager"
> "web3-core-subscriptions"
> "web3-eth"
> "web3-eth-abi"
> "web3-eth-accounts"
> "web3-eth-contract"
> "web3-eth-ens"
> "web3-eth-iban"
> "web3-eth-personal"
> "web3-net"
> "web3-providers-http"
> "web3-providers-ipc"
> "web3-providers-ws"
> "web3-shh"
> "web3-utils"
> "ffjavascript"
> "wasmbuilder"
> "wasmcurves"
> "circom_tester"
> "ethereum-ens"
> "fastfile"
> "ffjavascript"
> "r1csfile"
> "ffjavascript"
> "wasmbuilder"
> "wasmcurves"
> "snarkjs"
> "ffjavascript"
> "r1csfile"
> "wasmbuilder"
> "wasmcurves"
> "wasmbuilder"
> "wasmcurves"
> "web3"
> "web3-bzz"
> "web3-core"
> "web3-core-helpers"
> "web3-core-method"
> "web3-core-promievent"
> "web3-core-requestmanager"
> "web3-core-subscriptions"
> "web3-eth"
> "web3-eth-abi"
> "web3-eth-accounts"
> "web3-eth-contract"
> "web3-eth-ens"
> "web3-eth-iban"
> "web3-eth-personal"
> "web3-net"
> "web3-providers-http"
> "web3-providers-ipc"
> "web3-providers-ws"
> "web3-shh"
> "web3-utils"
```

To be fair, this is just a quick scan of top-level package.json file. I am sure in the child packages there is more.

**Pull request closed without merging**
