### PR TITLE
Save invalid blocks in optimist database

### PR DESCRIPTION
**Pull request by daveroga**
Fixes: #813 

We will store information about invalid blocks in optimist and the type of challenge they generate:

- Created collection `invalid_blocks` in optimist.
- `invalid_blocks` will store this information when an invalid block is detected:
   - invalidCode
   - invalidMessage
   - block data
- Fixed adversary test check balances when calling `npm run adversary-test-all`

### CODE REVIEW

**Comment by druiz0992** [comment]
Do we store address of challenger?

**Comment by daveroga** [comment]
> Do we store address of challenger?
We store the invalid block once it is produced and detected by optimist. At this time we don't know the challenger that will pick the challenge.
I could investigate if I can get the challenger from the emit Rollback detected from the Challenges contract in the optimist, but the sender is not passed now in the event. We could pass it in the Rollback event to know the challenger and then store it in the invalid block stored previously in the optimist database.

**Review by israelboudoux — APPROVED** [review]
LGTM

**Comment by druiz0992** [comment]
@daveroga it would be would if we could get the challenger address for statistics

**Review by druiz0992 — APPROVED** [review]

**Pull request merged**
