### PR TITLE
github action refactored to test tx-gas.mjs test suites

### PR DESCRIPTION
**Pull request by LijuJoseJJ**

### CODE REVIEW

**Review by Westlad — COMMENTED** [review]
To run test-gas properly, we need to set the number of transactions in a block to be 32 (rather than the 2 we usually use for the other tests) but I can figure out if this is being done here.

**Comment by LijuJoseJJ** [comment]
> To run test-gas properly, we need to set the number of transactions in a block to be 32 (rather than the 2 we usually use for the other tests) but I can't figure out if this is being done here.

correction done

**Comment by Westlad** [comment]
I think this was caused by me removing the `Geth`-based tests.  Now that we run Geth in a separate docker project, these tests no longer work.

**Comment by LijuJoseJJ** [comment]
> I think this was caused by me removing the `Geth`-based tests. Now that we run Geth in a separate docker project, these tests no longer work.

conflict resolved

**Review by Westlad — APPROVED** [review]

**Pull request merged**
