### PR TITLE
(nightfall-browser) shared worker implemented for generate proof

### LINKED ISSUE #611: Add web worker to offload proof computation and support multi threading

### PR DESCRIPTION
**Pull request by LijuJoseJJ**
This PR implemented a sharedWorker which offload work on generate proof to different thread
fixes #611 

This PR also does a small refactor to fetch files from public bucket, aws sdk in not needed we can use browser fetch api itself

### CODE REVIEW

**Comment by israelboudoux** [comment]
Hey @LijuJoseJJ, is this PR still needed? if so, could you explain why it has a DNM tag and when you expect to merge it?

Thank you!

**Comment by LijuJoseJJ** [comment]
Hi @israelboudoux 
after discussing with @IlyasRidhuan 
this PR is needed for wallet 2.0. I added a new label to avoid confusion

**Comment by israelboudoux** [comment]
Hi @LijuJoseJJ, do you think this PR can be merged anytime soon?

**Comment by Westlad** [comment]
Closing as an aged PR

**Pull request closed without merging**
