### PR TITLE
fix: Adding listener for queues on errors

### PR DESCRIPTION
**Pull request by israelboudoux**
## What does this implement/fix? Explain your changes.
This fixes an issue that can happen when errors aren't properly caught by the queues. The queues being used are emitters and when there isn't a listener for an 'error' event for that queue and an error happens, the application crashes. 

Follows the log of a test performed locally:

```
optimist_1       | [2023-01-06 14:25:49.066] DEBUG: Block Assembler - about to make a new block
optimist_1       |     correlationId: "579dd1c6-1ad5-448e-89f3-90c1173cc75c"
optimist_1       | file:///app/node_modules/@polygon-nightfall/common-files/utils/block-utils.mjs:27
optimist_1       |   const proposerPacked = generalise(proposer).hex(20).slice(2);
optimist_1       |                                              ^
optimist_1       | 
optimist_1       | TypeError: Cannot read properties of undefined (reading 'hex')
optimist_1       |     at packBlockInfo (file:///app/node_modules/@polygon-nightfall/common-files/utils/block-utils.mjs:27:46)
optimist_1       |     at calcBlockHash (file:///app/node_modules/@polygon-nightfall/common-files/utils/block-utils.mjs:45:22)
optimist_1       |     at Function.calcHash (file:///app/src/classes/block.mjs:218:12)
optimist_1       |     at Function.build (file:///app/src/classes/block.mjs:138:28)
optimist_1       |     at runMicrotasks (<anonymous>)
optimist_1       |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
optimist_1       |     at async conditionalMakeBlock (file:///app/src/services/block-assembler.mjs:166:23)
optimist_1       | Emitted 'error' event on Queue instance at:
optimist_1       |     at next (/app/node_modules/queue/index.js:108:14)
optimist_1       |     at /app/node_modules/queue/index.js:150:14
optimist_1       |     at runMicrotasks (<anonymous>)
optimist_1       |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
nightfall_3_optimist_1 exited with code 1
```

## Does this close any currently open issues?
No

## What commands can I run to test the change? 
The current ones in Github Actions.

## Any other comments?
No

### CODE REVIEW

**Comment by israelboudoux** [comment]
I choose the worst name ever for that function, if someone has a better suggestion, pls tell me!

**Comment by israelboudoux** [comment]
> I chose the worst name ever for that function, if someone has a better suggestion, pls tell me!

I just changed to `createQueue`, makes more sense.

**Comment by pawelgrzybek** [comment]
Maybe we should create our own instance of the queue that encapsulates error handling, and use it across?

**Comment by israelboudoux** [comment]
> Maybe we should create our own instance of the queue that encapsulates error handling, and use it across?

It is used just in three points. I'd go for that approach if we used it more extensively.

**Review by Westlad — APPROVED** [review]

**Review by imagobea — APPROVED** [review]
LGTM :+1:

**Pull request merged**
